/**
 * Generate + apply the launchd plist for the propagate watcher.
 *
 * The plist's WatchPaths drives which directories launchd notifies on. V2
 * derives WatchPaths from discovered workspaces (each workspace's root
 * AND its `docs/` subdir when present) instead of hardcoded paths.
 *
 * Atomic write: write to a temp file, then rename. This avoids leaving
 * a partial plist that would brick launchd auto-load.
 */

import { writeFile, rename, readFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { execSync } from "node:child_process";

import { SEARCH_ROOTS, WORKSPACES, SKILL_DIR } from "./config.mjs";

const HOME = os.homedir();
// Label is configurable so a rename does not silently break doctor's own checks.
// It did exactly that on 2026-08-11 when agents were standardised to
// com.tathya.<domain>.<job>: the watcher kept running under the new label while
// cli.mjs still grepped launchctl for the old one and reported "plist loaded: FAIL".
export const LABEL = process.env.PROPAGATE_LABEL || "com.tathya.propagate.watcher";
const PLIST_PATH = path.join(HOME, "Library", "LaunchAgents", `${LABEL}.plist`);

function escapeXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function buildPlist({ workspaces, nodeBin, watcherScript, skillDir }) {
  // WatchPaths: each workspace's root + its docs/ subdir if present.
  const watchPaths = new Set();
  for (const ws of workspaces) {
    watchPaths.add(ws.root);
    const docsDir = path.join(ws.root, "docs");
    if (existsSync(docsDir)) watchPaths.add(docsDir);
  }
  const watchPathStrings = [...watchPaths]
    .sort()
    .map((p) => `    <string>${escapeXml(p)}</string>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(nodeBin)}</string>
    <string>${escapeXml(watcherScript)}</string>
  </array>

  <!-- Fire on any change in these directories. launchd coalesces rapid
       events; the watcher's lock makes concurrent invocations safe.
       Generated by lib/plist.mjs from discovered workspaces. -->
  <key>WatchPaths</key>
  <array>
${watchPathStrings}
  </array>

  <!-- Don't restart on exit; we run once per file event. -->
  <key>RunAtLoad</key>
  <false/>

  <key>KeepAlive</key>
  <false/>

  <!-- Throttle: launchd won't fire more than once per N seconds even if
       multiple file events arrive. Coalesces editor bursts. -->
  <key>ThrottleInterval</key>
  <integer>5</integer>

  <!-- Periodic poll. WatchPaths only fires for direct-child changes of
       listed dirs; deeply-nested edits (e.g. lib/pricing.ts under a
       project root) don't always trigger. StartInterval guarantees a
       full scan every N seconds regardless. Replaces the accidental
       feedback-loop polling that arose from unconditional ledger MD
       re-render. -->
  <key>StartInterval</key>
  <integer>60</integer>

  <key>StandardOutPath</key>
  <string>${escapeXml(path.join(skillDir, "watcher.stdout.log"))}</string>

  <key>StandardErrorPath</key>
  <string>${escapeXml(path.join(skillDir, "watcher.stderr.log"))}</string>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
}

/**
 * Regenerate the plist from currently-discovered workspaces.
 * Atomic write via temp+rename. Does NOT reload launchd.
 * @returns {{ path: string, content: string, watchedRoots: string[] }}
 */
export async function regeneratePlist({ workspaces = WORKSPACES } = {}) {
  // process.execPath, not a literal. launchd gets a bare environment with no
  // nvm/asdf shims, so the plist must name an absolute interpreter -- but
  // "/opt/homebrew/bin/node" is this machine's Homebrew layout and does not
  // exist on an Intel Mac, a Linux box, or under a version manager. The
  // interpreter currently running this code is by definition one that works.
  const nodeBin = process.execPath;
  const watcherScript = path.join(SKILL_DIR, "watcher.mjs");
  const content = buildPlist({
    workspaces,
    nodeBin,
    watcherScript,
    skillDir: SKILL_DIR,
  });

  await mkdir(path.dirname(PLIST_PATH), { recursive: true });
  const tmpPath = `${PLIST_PATH}.tmp.${process.pid}.${Date.now()}`;
  await writeFile(tmpPath, content, "utf8");
  await rename(tmpPath, PLIST_PATH);

  return {
    path: PLIST_PATH,
    content,
    watchedRoots: workspaces.map((ws) => ws.root),
  };
}

/**
 * Reload launchd: bootout then bootstrap. Safe to call repeatedly.
 * Returns trimmed stdout.
 */
export function reloadLaunchd() {
  const uid = process.getuid ? process.getuid() : 501;
  const lines = [];
  // bootout may fail if not loaded — that's fine.
  try {
    const out = execSync(`launchctl bootout gui/${uid} "${PLIST_PATH}"`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    lines.push(`bootout: ${out.trim() || "(ok)"}`);
  } catch (err) {
    lines.push(`bootout (skip): ${err.message.split("\n")[0]}`);
  }
  try {
    const out = execSync(`launchctl bootstrap gui/${uid} "${PLIST_PATH}"`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    lines.push(`bootstrap: ${out.trim() || "(ok)"}`);
  } catch (err) {
    lines.push(`bootstrap FAILED: ${err.message.split("\n")[0]}`);
    throw new Error(lines.join("\n"));
  }
  return lines.join("\n");
}

export { PLIST_PATH };
