/**
 * Generate + apply the launchd plist for the propagate watcher.
 *
 * The plist's WatchPaths drives which directories launchd notifies on. V2
 * derives WatchPaths from discovered workspaces (each workspace's root
 * AND its `docs/` subdir when present) instead of hardcoded paths.
 *
 * Atomic write: write to a temp file, then rename. This avoids leaving
 * a partial plist that would brick launchd auto-load.
 */

import { writeFile, rename, readFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { execSync } from "node:child_process";

import { SEARCH_ROOTS, WORKSPACES, SKILL_DIR, STATE_DIR, STATE_DIR_EXPLICIT } from "./config.mjs";

const HOME = os.homedir();
// Label is configurable so a rename does not silently break doctor's own checks.
// It did exactly that on 2026-08-11 when agents were standardised to
// com.tathya.<domain>.<job>: the watcher kept running under the new label while
// cli.mjs still grepped launchctl for the old one and reported "plist loaded: FAIL".
export const LABEL = process.env.PROPAGATE_LABEL || "com.tathya.propagate.watcher";
// PROPAGATE_STATE_DIR (lib/config.mjs) relocates the plist alongside state,
// lock, heartbeat and watcher log -- N14 (docs/ISSUES.md): a scoped test run
// used to write the REAL plist (fixed to ~/Library/LaunchAgents) with
// whatever discovery.mjs found in the scoped tree, which could be 0
// workspaces. When STATE_DIR is unset (the default), this resolves
// byte-identically to the pre-existing ~/Library/LaunchAgents/<LABEL>.plist.
// EXPLICIT override only. The plist is a launchd integration point, not state: it
// belongs in ~/Library/LaunchAgents because that is where launchd looks. Keying off
// `STATE_DIR` being non-null was correct only while its default was null; once it
// gained a real default (2026-08-20) that would have silently relocated the plist
// somewhere nothing loads it. A scoped/test run still redirects it, which is the
// N14 property this preserves.
const PLIST_DIR = STATE_DIR_EXPLICIT ? STATE_DIR : path.join(HOME, "Library", "LaunchAgents");
const PLIST_PATH = path.join(PLIST_DIR, `${LABEL}.plist`);

/**
 * Resolve a stable node interpreter path for ProgramArguments.
 *
 * `process.execPath` resolves symlinks, so under Homebrew it returns the
 * VERSION-PINNED real path (e.g. `/opt/homebrew/Cellar/node/25.9.0_1/bin/node`)
 * rather than the stable `/opt/homebrew/bin/node` symlink `brew upgrade node`
 * repoints. A plist baking in the resolved path breaks silently on the next
 * upgrade — launchd tries to exec a binary that no longer exists at that path,
 * and nothing prints why. Measured 2026-08-20: the installed monitor plist
 * already carried `.../Cellar/node/25.9.0_1/bin/node`, the *current* version —
 * meaning it was already one `brew upgrade` away from breaking, not yet broken.
 *
 * `command -v node` resolves through PATH the way an interactive shell would,
 * which is normally the unversioned symlink. Fall back to `process.execPath`
 * only if that lookup fails (no shell, no PATH, no `node` on PATH) — a working
 * plist beats a stable-but-wrong one.
 */
function resolveStableNodeBin() {
  try {
    const out = execSync("command -v node", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (out && !out.includes("/Cellar/")) return out;
  } catch {
    // no shell, no PATH entry for node -- fall through to execPath
  }
  return process.execPath;
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function buildPlist({ workspaces, nodeBin, watcherScript, skillDir }) {
  // WatchPaths: each workspace's root + its docs/ subdir if present.
  const watchPaths = new Set();
  for (const ws of workspaces) {
    watchPaths.add(ws.root);
    const docsDir = path.join(ws.root, "docs");
    if (existsSync(docsDir)) watchPaths.add(docsDir);
  }
  const watchPathStrings = [...watchPaths]
    .sort()
    .map((p) => `    <string>${escapeXml(p)}</string>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(nodeBin)}</string>
    <string>${escapeXml(watcherScript)}</string>
  </array>

  <!-- Fire on any change in these directories. launchd coalesces rapid
       events; the watcher's lock makes concurrent invocations safe.
       Generated by lib/plist.mjs from discovered workspaces. -->
  <key>WatchPaths</key>
  <array>
${watchPathStrings}
  </array>

  <!-- Don't restart on exit; we run once per file event. -->
  <key>RunAtLoad</key>
  <false/>

  <key>KeepAlive</key>
  <false/>

  <!-- Throttle: launchd won't fire more than once per N seconds even if
       multiple file events arrive. Coalesces editor bursts. -->
  <key>ThrottleInterval</key>
  <integer>5</integer>

  <!-- Periodic poll. WatchPaths only fires for direct-child changes of
       listed dirs; deeply-nested edits (e.g. lib/pricing.ts under a
       project root) don't always trigger. StartInterval guarantees a
       full scan every N seconds regardless. Replaces the accidental
       feedback-loop polling that arose from unconditional ledger MD
       re-render. -->
  <key>StartInterval</key>
  <integer>60</integer>

  <key>StandardOutPath</key>
  <string>${escapeXml(path.join(skillDir, "watcher.stdout.log"))}</string>

  <key>StandardErrorPath</key>
  <string>${escapeXml(path.join(skillDir, "watcher.stderr.log"))}</string>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
}

/**
 * Regenerate the plist from currently-discovered workspaces.
 * Atomic write via temp+rename. Does NOT reload launchd.
 *
 * Refuses to write when `workspaces` is empty (N14, docs/ISSUES.md): a plist
 * with zero WatchPaths is never a legitimate outcome -- it is always either a
 * misconfiguration (bad SEARCH_ROOTS) or a deliberately scoped run, and
 * writing it over a working plist silently disarms file-event watching
 * (launchd stays loaded but only fires on the StartInterval poll). This
 * single guard would have prevented N14 outright.
 *
 * @returns {Promise<{ ok: true, path: string, content: string, watchedRoots: string[] } | { ok: false, path: string, error: string }>}
 */
export async function regeneratePlist({ workspaces = WORKSPACES } = {}) {
  const watchedRoots = workspaces.map((ws) => ws.root);
  if (watchedRoots.length === 0) {
    return {
      ok: false,
      path: PLIST_PATH,
      error:
        "refusing to write a plist with 0 watch roots -- discovery found no workspaces " +
        "(check PROPAGATE_SEARCH_ROOTS, or this is a deliberately scoped run and the real " +
        "plist should not be touched)",
    };
  }

  // Derived, not a literal: launchd gets a bare environment with no nvm/asdf
  // shims, so the plist must name an absolute interpreter, and it must be one
  // that survives a `brew upgrade node` (resolveStableNodeBin above) rather
  // than the version-pinned real path `process.execPath` alone would give.
  const nodeBin = resolveStableNodeBin();
  const watcherScript = path.join(SKILL_DIR, "watcher.mjs");
  const content = buildPlist({
    workspaces,
    nodeBin,
    watcherScript,
    skillDir: SKILL_DIR,
  });

  await mkdir(path.dirname(PLIST_PATH), { recursive: true });
  const tmpPath = `${PLIST_PATH}.tmp.${process.pid}.${Date.now()}`;
  await writeFile(tmpPath, content, "utf8");
  await rename(tmpPath, PLIST_PATH);

  return {
    ok: true,
    path: PLIST_PATH,
    content,
    watchedRoots,
  };
}

/**
 * Reload launchd: bootout then bootstrap. Safe to call repeatedly.
 * Returns trimmed stdout.
 */
export function reloadLaunchd() {
  const uid = process.getuid ? process.getuid() : 501;
  const lines = [];
  // bootout may fail if not loaded — that's fine.
  try {
    const out = execSync(`launchctl bootout gui/${uid} "${PLIST_PATH}"`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    lines.push(`bootout: ${out.trim() || "(ok)"}`);
  } catch (err) {
    lines.push(`bootout (skip): ${err.message.split("\n")[0]}`);
  }
  try {
    const out = execSync(`launchctl bootstrap gui/${uid} "${PLIST_PATH}"`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    lines.push(`bootstrap: ${out.trim() || "(ok)"}`);
  } catch (err) {
    lines.push(`bootstrap FAILED: ${err.message.split("\n")[0]}`);
    throw new Error(lines.join("\n"));
  }
  return lines.join("\n");
}

export { PLIST_PATH };

// ─────────────────────────────────────────────────────────────────────────────
// The monitor's plist (2026-08-17).
//
// Deliberately a SEPARATE label and path from everything above. The watcher was
// retired 2026-08-14 and `LABEL` still defaults to its name; generating the
// monitor through `regeneratePlist` would write over the retired job's plist,
// resurrect its label, and break `doctor`'s retired-watcher assertions — three
// bad outcomes from one convenience.
//
// It reuses the two things worth reusing: the WatchPaths derivation, and the
// zero-watch-root refusal (N14). It does NOT reuse the watcher's intervals:
//   ThrottleInterval 300 (not 5)  — coalesce editor bursts far harder; the
//                                   payload is a full derivation costing ~790ms
//                                   warm and ~5.1s cold under launchd (measured
//                                   2026-08-17), not a cheap mtime diff.
//   StartInterval   1800 (not 60) — 48 runs/day, not 1,440. WatchPaths only
//                                   fires on direct-child changes (see the
//                                   comment in the watcher template above), so
//                                   a floor is still required — but a missed
//                                   trigger costs nothing here, because the
//                                   payload derives from content rather than
//                                   diffing a remembered baseline.
// ─────────────────────────────────────────────────────────────────────────────

export const MONITOR_LABEL = process.env.PROPAGATE_MONITOR_LABEL || "com.tathya.propagate.monitor";
// Already exported at the foot of this file. doctor reads it to tell "armed"
// from "generated but not armed" (2026-08-22) — that distinction is the whole
// reason the monitor's liveness probe can be a check() at all: a monitor that
// was never armed must never fail a fresh install, while an ARMED monitor
// that has gone quiet must.
const MONITOR_PLIST_PATH = path.join(PLIST_DIR, `${MONITOR_LABEL}.plist`);

/** WatchPaths for a workspace set: each root, plus its docs/ when present. */
export function watchPathsFor(workspaces) {
  const paths = new Set();
  for (const ws of workspaces) {
    paths.add(ws.root);
    const docsDir = path.join(ws.root, "docs");
    if (existsSync(docsDir)) paths.add(docsDir);
  }
  return [...paths];
}

/**
 * Generate the monitor's plist. Writes the FILE only — never runs launchctl.
 * Loading it is a separate, deliberate step: touching launchd is a one-way door
 * and belongs to the human, per SKILL.md's contract.
 *
 * @returns {Promise<{ok: true, path: string, watchPaths: string[]} | {ok: false, path: string, error: string}>}
 */
export async function writeMonitorPlist({ workspaces = WORKSPACES, stateDir = STATE_DIR } = {}) {
  const watchPaths = watchPathsFor(workspaces);
  if (watchPaths.length === 0) {
    // Same refusal, same reason as regeneratePlist. A monitor watching nothing
    // is worse than no monitor: launchd stays loaded and the only thing still
    // firing is the poll, so it looks alive while watching nothing.
    return {
      ok: false,
      path: MONITOR_PLIST_PATH,
      error:
        "refusing to write a monitor plist with 0 watch roots -- discovery found no " +
        "workspaces (check PROPAGATE_SEARCH_ROOTS, or this is a deliberately scoped run)",
    };
  }

  const logDir = stateDir || path.join(HOME, ".propagate");
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(MONITOR_LABEL)}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(resolveStableNodeBin())}</string>
    <string>${escapeXml(path.join(SKILL_DIR, "cli.mjs"))}</string>
    <string>monitor</string>
  </array>

  <key>WatchPaths</key>
  <array>
${watchPaths.map((p) => `    <string>${escapeXml(p)}</string>`).join("\n")}
  </array>

  <key>RunAtLoad</key>
  <false/>
  <key>KeepAlive</key>
  <false/>

  <!-- 300s, not the watcher's 5s: the payload is a full 770ms derivation. -->
  <key>ThrottleInterval</key>
  <integer>300</integer>

  <!-- 1800s = 48 runs/day. The watcher's 60s meant 1,440/day and 99.2% no-ops;
       the no-op ratio here will be similar and that is fine, because a no-op
       reads files and exits rather than touching a baseline that can invent
       drift. -->
  <key>StartInterval</key>
  <integer>1800</integer>

  <key>StandardOutPath</key>
  <string>${escapeXml(path.join(logDir, "monitor.stdout.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(path.join(logDir, "monitor.stderr.log"))}</string>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
  await mkdir(path.dirname(MONITOR_PLIST_PATH), { recursive: true });
  await writeFile(MONITOR_PLIST_PATH, body, "utf8");
  return { ok: true, path: MONITOR_PLIST_PATH, watchPaths };
}

export { MONITOR_PLIST_PATH };

// ─────────────────────────────────────────────────────────────────────────────
// The digest's plist (generator added 2026-08-20).
//
// Until now this plist was hand-maintained: nothing in this file ever wrote it
// (cli.mjs's `reload` comment already recorded "lib/plist.mjs never touches
// the digest plist -- grep confirms it"), so the installed copy hardcoded
// `/opt/homebrew/bin/node` and the skill's absolute path by hand. A relocated
// skill or an intentional Homebrew-path change would silently strand it --
// the same G48 shape as the pre-commit hooks this lane also fixes.
//
// No WatchPaths and no zero-watch-root refusal: the digest runs on a fixed
// daily schedule (StartCalendarInterval), not on file events, so there is
// nothing analogous to N14's "0 roots" misconfiguration to refuse.
// ─────────────────────────────────────────────────────────────────────────────

export const DIGEST_LABEL = process.env.PROPAGATE_DIGEST_LABEL || "com.tathya.propagate.digest";
const DIGEST_PLIST_PATH = path.join(PLIST_DIR, `${DIGEST_LABEL}.plist`);

/**
 * Generate the digest's plist. Writes the FILE only -- never runs launchctl.
 * Loading it is a separate, deliberate step, same contract as writeMonitorPlist.
 *
 * @returns {Promise<{ok: true, path: string}>}
 */
export async function writeDigestPlist({ stateDir = STATE_DIR } = {}) {
  const logDir = stateDir || path.join(HOME, ".propagate");
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(DIGEST_LABEL)}</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${escapeXml(HOME)}</string>
  </dict>

  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(resolveStableNodeBin())}</string>
    <string>${escapeXml(path.join(SKILL_DIR, "digest.mjs"))}</string>
  </array>

  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>9</integer>
    <key>Minute</key>
    <integer>0</integer>
  </dict>

  <key>RunAtLoad</key>
  <false/>
  <key>KeepAlive</key>
  <false/>

  <key>StandardOutPath</key>
  <string>${escapeXml(path.join(logDir, "digest.stdout.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(path.join(logDir, "digest.stderr.log"))}</string>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
  await mkdir(path.dirname(DIGEST_PLIST_PATH), { recursive: true });
  const tmpPath = `${DIGEST_PLIST_PATH}.tmp.${process.pid}.${Date.now()}`;
  await writeFile(tmpPath, body, "utf8");
  await rename(tmpPath, DIGEST_PLIST_PATH);
  return { ok: true, path: DIGEST_PLIST_PATH };
}

export { DIGEST_PLIST_PATH };
