/**
 * The decision tier of the graph, and the two defects that let it sit EMPTY while
 * 1234 tests passed and `graph-index --json` reported `decisions: 45`.
 *
 * MEASURED 2026-08-29, before the fix:
 *   node table:  file 762 · project 45 · decision 0
 *   stats:       decisions 45 · affects 0 · decisionsFiles 8
 *
 * DEFECT 1 — `defaultDecisionsFiles` looked only at `<workspace>/docs/DECISIONS.md`
 * and `<workspace>/DECISIONS.md`. Since the 2026-08-21 move those are the 15-line
 * "# DECISIONS.md — moved … Do not edit this file" pointer stubs, 0 `##` headings
 * each. Every real ledger lives at `propagation/state/<project>/DECISIONS.md`.
 *
 * DEFECT 2 — and this is why defect 1 survived — `stats.decisions` was
 * `nodes.length - fileKeys.length`, i.e. "everything that is not a file". The
 * PROJECT tier is also not a file, so 45 projects were reported as 45 decisions,
 * a number that looks entirely healthy. graph-index.mjs:147 promises this stat
 * exists so that "zero decisions is visibly a finding rather than a silent pass";
 * computed that way it did the exact opposite. rule:enforcement-watches-itself.
 *
 * WHY THESE TESTS ARE SHAPED LIKE THIS. The whole suite was green through both
 * defects, so an assertion on "the build succeeds" is worthless here. Each test
 * below asserts on STORED CONTENT — rows in the sqlite node/edge tables — and the
 * project-tier test exists specifically so that reverting defect 2 goes red rather
 * than being masked by the projects that are legitimately present.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";

const SKILL_DIR = fileURLToPath(new URL("../../", import.meta.url));
const GRAPH_INDEX_PATH = path.join(SKILL_DIR, "lib/graph/graph-index.mjs");

const REAL_ENTRY = `# proj — Decisions

## 2026-08-29: the thing was chosen over the other thing

**What:** a real entry with a real Affects line.
**Why:** so the AFFECTS edge has somewhere to point.
**Affects:** proj
`;

/** The exact shape the 2026-08-21 move left at every workspace root. */
const POINTER_STUB = `# DECISIONS.md — moved

This file now lives at \`propagation/state/workspace/DECISIONS.md\`.

Do not edit this file. Edit the target.
`;

/**
 * A workspace in the v3 layout: a pointer stub at the legacy path, and the real
 * ledger under propagation/state/<project>/. That is the live tree's shape, and
 * it is the configuration in which the old resolver found only the stub.
 */
async function buildFixture() {
  const stateDir = await mkdtemp(path.join(tmpdir(), "gi-decisions-state-"));
  const workDir = await mkdtemp(path.join(tmpdir(), "gi-decisions-work-"));
  const ws = path.join(workDir, "ws");
  await mkdir(path.join(ws, "docs"), { recursive: true });
  await mkdir(path.join(ws, "proj"), { recursive: true });
  await mkdir(path.join(ws, "propagation", "state", "proj"), { recursive: true });
  await writeFile(path.join(ws, "docs", "DECISIONS.md"), POINTER_STUB);
  await writeFile(path.join(ws, "propagation", "state", "proj", "DECISIONS.md"), REAL_ENTRY);

  // A declared edge is REQUIRED, not decoration. Project nodes are derived from
  // FILE nodes (`projectOf(abs)`), file nodes come from reconcile()'s edges, and
  // edges come from a sidecar. Without one the fixture has zero projects — and
  // with zero projects `nodes.length - fileKeys.length` happens to equal the
  // decision count, so the buggy formula would PASS. The project tier is the
  // thing that makes defect 2 observable at all.
  await writeFile(
    path.join(ws, ".propagates.yml"),
    [
      "workspace: true",
      "sources:",
      "  proj/SOURCE.md:",
      "    propagates_to:",
      "      - path: proj/DOWNSTREAM.md",
      "        why: fixture edge, so a file node and therefore a project node exists",
      "        kind: prose",
      "",
    ].join("\n"),
  );
  await writeFile(path.join(ws, "proj", "SOURCE.md"), "# source\n");
  await writeFile(path.join(ws, "proj", "DOWNSTREAM.md"), "# downstream\n");

  const dbPath = path.join(stateDir, "graph-index.db");
  const script = `
    import { buildModel, emitSqlite } from ${JSON.stringify(GRAPH_INDEX_PATH)};
    const model = await buildModel([{ root: ${JSON.stringify(ws)} }]);
    emitSqlite(model, ${JSON.stringify(dbPath)});
    console.log(JSON.stringify(model.stats));
  `;
  const r = spawnSync(process.execPath, ["--input-type=module", "-e", script], {
    encoding: "utf8",
    env: { ...process.env, PROPAGATE_STATE_DIR: stateDir },
  });
  if (r.status !== 0) throw new Error(`fixture build failed: ${r.stderr}`);
  return { stateDir, workDir, dbPath, stats: JSON.parse(r.stdout.trim().split("\n").pop()) };
}

async function cleanup({ stateDir, workDir }) {
  await rm(stateDir, { recursive: true, force: true, maxRetries: 10, retryDelay: 50 });
  await rm(workDir, { recursive: true, force: true, maxRetries: 10, retryDelay: 50 });
}

test("the v3 ledger is indexed — a decision node exists, not just a parsed count", async () => {
  const fx = await buildFixture();
  try {
    const db = new DatabaseSync(fx.dbPath, { readOnly: true });
    const rows = db.prepare("select id, kind from node where kind = 'decision'").all();
    db.close();
    // RED before the fix: defaultDecisionsFiles resolved only the pointer stub,
    // which parses to zero entries, so this table was empty.
    assert.ok(rows.length >= 1, `expected >=1 decision node, got ${rows.length}`);
  } finally {
    await cleanup(fx);
  }
});

test("stats.decisions counts the KIND, and is not inflated by the project tier", async () => {
  const fx = await buildFixture();
  try {
    const db = new DatabaseSync(fx.dbPath, { readOnly: true });
    const stored = db.prepare("select count(*) c from node where kind = 'decision'").get().c;
    const projects = db.prepare("select count(*) c from node where kind = 'project'").get().c;
    db.close();
    // The load-bearing assertion: the reported number must equal what is STORED.
    // `nodes.length - fileKeys.length` satisfies neither of these when any project
    // node exists, which is always.
    assert.equal(fx.stats.decisions, stored, "stats.decisions must equal stored decision nodes");
    assert.ok(projects >= 1, "fixture must contain a project tier, or this cannot catch the defect");
  } finally {
    await cleanup(fx);
  }
});

test("a pointer stub contributes no decisions — absence is real, not a parse failure", async () => {
  const fx = await buildFixture();
  try {
    const db = new DatabaseSync(fx.dbPath, { readOnly: true });
    const paths = db.prepare("select distinct path from node where kind = 'decision'").all().map((r) => r.path);
    db.close();
    // Every decision must come from the v3 path. If a stub ever starts yielding
    // entries, the parser has begun reading a "moved" signpost as content — the
    // N56 failure, one register over.
    for (const p of paths) {
      assert.match(String(p), /propagation[/\\]state[/\\]/, `decision sourced from a non-v3 path: ${p}`);
    }
  } finally {
    await cleanup(fx);
  }
});
