/**
 * migrate-pointer-stub.test.mjs — the stub generator, and the round-trip its own
 * docstring promises.
 *
 * `renderPointerStub` had ZERO tests when this file was written (2026-09-28),
 * which matters more than usual because of what its docstring claims:
 *
 *   "The wording deliberately contains 'pointer stub' so `isPointerStub` matches
 *    it on a later pass; a stub this tool cannot re-recognise would be migrated
 *    over itself next time."
 *
 * That is a coupling between a WRITER and a READER in the same module, stated in
 * prose and asserted nowhere — `rule:adversarial-review-reads-the-ledger`'s
 * exact shape, a promise in one place that another has to keep. Any rewording of
 * the generated text could have broken it silently, and the failure mode is a
 * migration destroying the state it just moved.
 *
 * `rule:name-what-no-test-executes`: the generator ran in production ten
 * workspaces ago and no test had ever called it.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  renderPointerStub,
  isPointerStub,
  stubTarget,
} from "../../lib/migrate/workspace.mjs";

const OWN = "propagation/state/workspace/TODOS.md";
const PROJ = "propagation/state/somebody/STATE.md";

/**
 * Collapse the hard line wrapping before asserting on prose.
 *
 * The first version of the negative control below asserted
 * /every project in this workspace/ against the raw text and FAILED — the
 * generated paragraph wraps between "this" and "workspace,". The code was
 * correct; the test was matching a phrase across a newline. Worth keeping the
 * note: a source-text assertion on wrapped prose is a check that fails for a
 * reason unrelated to the property, which is its own kind of unreliable.
 */
const flat = (s) => s.replace(/\s+/g, " ");

function render(toRel) {
  return renderPointerStub({
    artifact: path.basename(toRel),
    toRel,
    fromRel: path.basename(toRel),
    workspaceName: "obsidian-vk-publish",
    sha: "abc1234",
  });
}

/** isPointerStub reads a PATH, so the text has to go through disk. */
function recognised(text) {
  const dir = mkdtempSync(path.join(tmpdir(), "stub-"));
  try {
    const f = path.join(dir, "STATE.md");
    writeFileSync(f, text);
    return { stub: isPointerStub(f), target: stubTarget(text) };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test("BOTH wordings are re-recognised by isPointerStub — or a migration overwrites its own stub", () => {
  for (const [label, toRel] of [["workspace-own", OWN], ["project", PROJ]]) {
    const r = recognised(render(toRel));
    assert.equal(r.stub, true, `${label} stub is not recognised as a stub — it would be migrated over`);
    assert.equal(r.target, toRel, `${label} stub's declared target must read back exactly`);
  }
});

test("a workspace's OWN artifact does not claim to be a project's state", () => {
  // The sentence the session in obsidian-vk-publish identified as what made a
  // deliberate layout read as the project layout — to them and to me, the same
  // day, in opposite directions. They fixed their copies; this is the producer.
  const own = render(OWN);
  assert.doesNotMatch(flat(own), /every project in this workspace/,
    "a file at state/workspace/ is the workspace's own register and belongs to no project");
  assert.match(own, /OWN register/);
  assert.match(flat(own), /beside, not among, the projects/);
  assert.match(own, /in this repo/,
    "a same-repo move must not tell the reader to look in another workspace");
});

test("a PROJECT's artifact keeps the original wording — the negative control", () => {
  // If this drifted too, the test above would prove nothing: it would just mean
  // the phrase had been deleted everywhere rather than routed correctly.
  const proj = render(PROJ);
  assert.match(flat(proj), /every project in this workspace/);
  assert.match(proj, /in the `obsidian-vk-publish` workspace/);
  assert.doesNotMatch(proj, /OWN register/);
});

test("both carry the way back to the history the move left behind", () => {
  for (const toRel of [OWN, PROJ]) {
    const t = render(toRel);
    assert.match(t, /git log --follow/, "the pre-move history is only reachable if the stub names how");
    assert.match(t, /abc1234/, "the pre-move SHA must appear — rule:state-and-decisions names it as the trade");
    assert.match(t, /Do not edit this file/);
  }
});

test("the branch is derived from the DESTINATION, so no caller can forget it", () => {
  // Same artifact name, same workspace, different destination -> different
  // paragraph. If this were a parameter, a call site could omit it and get the
  // wrong text with no error.
  assert.notEqual(render(OWN), render(PROJ));
  const nested = renderPointerStub({
    artifact: "TODOS.md",
    toRel: "deep/propagation/state/workspace/TODOS.md",
    fromRel: "TODOS.md",
    workspaceName: "w",
    sha: null,
  });
  assert.match(nested, /OWN register/, "the state/workspace/ segment must be recognised anywhere in the path");
});
